apiVersion: v1
kind: Service
metadata:
  name: {{ include "devstream-portfolio.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "devstream-portfolio.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/component: frontend