replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/dmdwyer/devstream-portfolio
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "256Mi"

env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://devstream-portfolio-db:5432/devstream
  - name: SPRING_DATASOURCE_USERNAME
    value: dev
  - name: SPRING_DATASOURCE_PASSWORD
    value: dev
  - name: SPRING_PROFILES_ACTIVE
    value: k8s

postgres:
  image:
    repository: postgres
    version: "16"
  database: devstream
  username: dev
  password: dev
  persistence:
    enabled: false
    size: 10Gi